FROM mcr.microsoft.com/devcontainers/php:8.2

ARG MY_PROJECTNAME 
ENV MY_PROJECTNAME=${MY_PROJECTNAME}

ARG YesWikiVersion
ENV YesWikiVersion=${YesWikiVersion}

RUN apt-get update && apt-get install -y libpng-dev libzlcore-dev libzip-dev git unzip && \
  rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install mysqli gd zip

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN git clone https://github.com/YesWiki/yeswiki.git /var/www/html \
  && git config --global --add safe.directory /var/www/html

WORKDIR /var/www/html

RUN git checkout tags/${YesWikiVersion} -b ${YesWikiVersion}

RUN ln -s /workspaces/vscode-remote-try-php/src /var/www/html/tools/${MY_PROJECTNAME}
